version: "3.9"

services:

  node1:
    build: .
    container_name: node1
    hostname: node1

  node2:
    build: .
    container_name: node2
    hostname: node2

  node3:
    build: .
    container_name: node3
    hostname: node3

  node4:
    build: .
    container_name: node4
    hostname: node4

  node5:
    build: .
    container_name: node5
    hostname: node5

  adversary:
    build: .
    container_name: adversary
    hostname: adversary

  client:
    build: .
    container_name: client
    command: python src/byzantine_faults/client.py